services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
     - "8080:80"
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: _docker/app/DockerFile
    volumes:
      - ./:/var/www
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: "3306"
      DB_DATABASE: test_app_laravel_docker
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db
    command: sh -lc "_docker/app/start.sh"
  db:
    image: mysql:9.4
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: test_app_laravel_docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306 
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  node:
    image: node:22
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports: 
      - 5173:5173
    command: sh -lc "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
  queue:
    build:
      context: .
      dockerfile: _docker/app/DockerFile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
      - app
    restart: unless-stopped
    command: sh -lc "php artisan queue:work database --sleep=0 --tries=3 --max-time=3600"
    # command: sh -lc "php artisan migrate --force || true && php artisan queue:work database --sleep=0 --tries=3 --max-time=3600"